[package]
name = "serverkit-cloudflare-worker-example"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
serverkit = { path = "../..", features = ["websocket"] }
serverkit-worker = { path = "../../adapters/worker", features = ["websocket"] }
worker = "0.8.5"

[workspace]
