[package]
name = "serverkit-worker"
version = "0.4.1"
edition = "2024"
description = "Cloudflare Workers adapter for ServerKit"
license.workspace = true
repository.workspace = true

[features]
default = []
websocket = ["serverkit/websocket"]

[dependencies]
serverkit = { version = "0.4.1", path = "../.." }

[target.'cfg(target_arch = "wasm32")'.dependencies]
futures-core = "0.3"
worker = "0.8.5"
